# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb7ae013f9fa026336fb9851ac494cf2b9ff92a1ec3d264b3594c8055700492defc29ccc96daec5123389be4eb7c6f432820f36f7179b392deb27e8b52e93c50

test:
  secret_key_base: 14805cd8202cfaa082b914a42829329558ac77aa8e0ee457c0141acff3b5c9bd5d4632dde4f79a897dbd29a6e7b6ed63c4dbb6f09d771994292fdd397c7c549d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
